language: python
python:
 - "3.6.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install coverage

script:
- pytest --cov

after_success:
- "codecov"
- coveralls

notifications:

  email: false
  